;;; test-smart-key.el --- self-checks for semantic activation -*- lexical-binding: t; -*-
;; Run: emacs --batch -Q --eval '(package-initialize)' -L . -l test/test-smart-key.el

(require 'ert)
(require 'cl-lib)
(require 'org)
(require 'button)

(when load-file-name
  (add-to-list 'load-path (expand-file-name ".." (file-name-directory load-file-name))))

(require 'supertag-smart-key)

(ert-deftest supertag-smart-key-prefers-supertag-context ()
  "A specific field context wins over broader properties at point."
  (with-temp-buffer
    (insert "status")
    (add-text-properties
     (point-min) (point-max)
     '(supertag-context t type :field-value tag-id "task"
       field-name "status" supertag-concept-node-id "concept-id"))
    (goto-char (point-min))
    (let (edited jumped)
      (cl-letf (((symbol-function 'supertag-view-node-edit-at-point)
                 (lambda () (interactive) (setq edited t)))
                ((symbol-function 'supertag-goto-node)
                 (lambda (&rest _) (setq jumped t))))
        (supertag-smart-key)
        (should edited)
        (should-not jumped)))
    (erase-buffer)
    (insert (propertize "field" 'supertag-context
                        '(:type :field :tag-id "task" :field-name "status")))
    (goto-char (point-min))
    (let (edited)
      (cl-letf (((symbol-function 'supertag-schema--edit-field-definition-at-point)
                 (lambda () (interactive) (setq edited t))))
        (supertag-smart-key)
        (should edited)))
    (erase-buffer)
    (insert (propertize "concept" 'supertag-context t
                        'supertag-concept-node-id "concept-id"))
    (goto-char (point-min))
    (let (opened)
      (cl-letf (((symbol-function 'supertag-goto-node)
                 (lambda (node-id &optional _) (setq opened node-id)))
                ((symbol-function 'supertag-view-node-edit-at-point)
                 (lambda () (interactive) (setq opened :edited))))
        (supertag-smart-key)
        (should (equal opened "concept-id"))))))

(ert-deftest supertag-smart-key-activates-concept-button-and-local-ret ()
  "Existing semantic properties and Emacs interaction primitives stay usable."
  (with-temp-buffer
    (insert (propertize "concept" 'supertag-concept-node-id "concept-id"))
    (goto-char (point-min))
    (let (opened)
      (cl-letf (((symbol-function 'supertag-goto-node)
                 (lambda (node-id &optional _) (setq opened node-id))))
        (supertag-smart-key)
        (should (equal opened "concept-id"))
        (erase-buffer)
        (insert (propertize "node" 'supertag-node-id "node-id"))
        (goto-char (point-min))
        (supertag-smart-key)
        (should (equal opened "node-id"))
        (erase-buffer)
        (insert (propertize "a" 'supertag-concept-node-id "concept-id"))
        (insert (propertize "b" 'supertag-ref-id "reference-id"))
        (goto-char (1- (point-max)))
        (supertag-smart-key)
        (should (equal opened "reference-id"))
        (erase-buffer)
        (insert (propertize "a" 'supertag-context t 'type :field-value))
        (insert (propertize "b" 'supertag-ref-id "reference-id"))
        (goto-char (1- (point-max)))
        (supertag-smart-key)
        (should (equal opened "reference-id"))))
    (erase-buffer)
    (let (pressed)
      (insert-text-button "button" 'action (lambda (_) (setq pressed :button)))
      (goto-char (point-min))
      (supertag-smart-key)
      (should (eq pressed :button)))
    (erase-buffer)
    (let ((map (make-sparse-keymap))
          pressed)
      (define-key map (kbd "RET") (lambda () (interactive) (setq pressed :ret)))
      (insert (propertize "legacy link" 'keymap map))
      (goto-char (point-min))
      (supertag-smart-key)
      (should (eq pressed :ret)))))

(ert-deftest supertag-smart-key-dispatches-table-cells ()
  "Table titles open source nodes; other cells keep their editor."
  (with-temp-buffer
    (setq major-mode 'supertag-view-table-mode)
    (insert (propertize "title" 'entity-id "node-id" 'col-key :title))
    (goto-char (point-min))
    (let (opened edited)
      (cl-letf (((symbol-function 'derived-mode-p)
                 (lambda (&rest modes) (memq 'supertag-view-table-mode modes)))
                ((symbol-function 'supertag-view-table-goto-node)
                 (lambda () (interactive) (setq opened t)))
                ((symbol-function 'supertag-view-table-edit-cell)
                 (lambda () (interactive) (setq edited t))))
        (supertag-smart-key)
        (should opened)
        (should-not edited)
        (erase-buffer)
        (insert (propertize "status" 'entity-id "node-id" 'col-key "status"))
        (goto-char (point-min))
        (setq opened nil)
        (supertag-smart-key)
        (should edited)
        (should-not opened)))))

(ert-deftest supertag-smart-key-opens-inline-tag-and-org-heading ()
  "Inline tags open their table; an Org heading opens its node view."
  (with-temp-buffer
    (org-mode)
    (insert "* Paper #research\n")
    (let (table node-view)
      (cl-letf (((symbol-function 'supertag-view-table)
                 (lambda (source &rest _) (setq table source)))
                ((symbol-function 'supertag-view-node--show-side)
                 (lambda (node-id) (setq node-view node-id)))
                ((symbol-function 'supertag-view-node--focus-view) #'ignore)
                ((symbol-function 'org-id-get-create) (lambda () "created-id")))
        (search-backward "research")
        (supertag-smart-key)
        (should (equal table '(:type :tag :value "research")))
        (beginning-of-line)
        (supertag-smart-key)
        (should (equal node-view "created-id"))
        (setq node-view nil table nil)
        (end-of-line)
        (supertag-smart-key)
        (should (equal node-view "created-id"))
        (should-not table)))))

(ert-deftest supertag-smart-key-does-not-treat-non-prose-hash-as-tag ()
  "Source blocks and Org priority markers are not implicit tag buttons."
  (with-temp-buffer
    (org-mode)
    (insert "#+begin_src emacs-lisp\n#not-a-tag\n#+end_src\n")
    (search-backward "not-a-tag")
    (should-error (supertag-smart-key) :type 'user-error))
  (with-temp-buffer
    (org-mode)
    (insert "* [#A] Priority\n")
    (search-backward "#A")
    (let (node-view table)
      (cl-letf (((symbol-function 'supertag-view-node--show-side)
                 (lambda (node-id) (setq node-view node-id)))
                ((symbol-function 'supertag-view-node--focus-view) #'ignore)
                ((symbol-function 'org-id-get-create) (lambda () "created-id"))
                ((symbol-function 'supertag-view-table)
                 (lambda (&rest _) (setq table t))))
        (supertag-smart-key)
        (should (equal node-view "created-id"))
        (should-not table)))))

(ert-deftest supertag-smart-key-prefers-org-link-over-url-fragment ()
  "A URL fragment stays an Org link instead of becoming an inline tag."
  (with-temp-buffer
    (org-mode)
    (insert "https://example.test/page#section")
    (search-backward "section")
    (let (opened table)
      (cl-letf (((symbol-function 'org-open-at-point)
                 (lambda (&rest _) (setq opened t)))
                ((symbol-function 'supertag-view-table)
                 (lambda (&rest _) (setq table t))))
        (supertag-smart-key)
        (should opened)
        (should-not table)))
    (erase-buffer)
    (insert (propertize "A" 'supertag-concept-node-id "concept-id"
                        'rear-nonsticky '(supertag-concept-node-id)))
    (let ((link-start (point)))
      (insert "[[id:node-id][Node]]")
      (goto-char link-start)
      (let (opened)
        (cl-letf (((symbol-function 'org-open-at-point)
                   (lambda (&rest _) (setq opened :link)))
                  ((symbol-function 'supertag-goto-node)
                   (lambda (&rest _) (setq opened :concept))))
          (supertag-smart-key)
          (should (eq opened :link)))))))

(ert-deftest supertag-smart-key-prefix-opens-assist-menu ()
  "A prefix argument delegates to the existing discoverable menu."
  (with-temp-buffer
    (let (opened)
      (cl-letf (((symbol-function 'supertag-menu)
                 (lambda () (interactive) (setq opened t))))
        (supertag-smart-key '(4))
        (should opened)))))

(when noninteractive
  (ert-run-tests-batch-and-exit))

(provide 'test-smart-key)
;;; test-smart-key.el ends here
